base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

recovery_behaviors: #[]
  - name: conservative_reset
    type: clear_costmap_recovery/ClearCostmapRecovery
  - name: agressive_reset
    type: clear_costmap_recovery/ClearCostmapRecovery
  
controller_frequency: 20.
planner_frequency: 1.  # 0. is only plan on a new goal or when local planner fails
planner_patience: 5.
controller_patience: 15.
recovery_behavior_enables: true
shutdown_costmaps: false
oscillation_timeout: 0.  # 0. is infinite
oscillation_distance: 0.5
map_planning_retries: -1.  # -1 is infinite

# Planners
GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.
  visualize_potential: true
  use_dijkstra: true  # although A* is faster, implementation pecularities here make it undesirable
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 220 #253 # how far from obstacle
  neutral_cost: 66 #40
  cost_factor:  1.55 #3
  publish_potential: True
  orientation_mode: 0.
  orientation_window_size: 1


DWAPlannerROS:
  use_dwa: true
  global_frame_id: odom

<<<<<<< HEAD
  max_vel_trans: 0.16 #0.1 /0.16
  min_vel_trans: 0.0
  max_vel_x: 1.7 #0.2 /1.7  
  min_vel_x: -0.6 #-0.15 /-0.6
  max_vel_y: 0.
  min_vel_y: 0.
  max_vel_theta: 1.6  # 0.5 /1.6 
  min_vel_theta: 0.5  # 0.5    /0.5
  acc_lim_x: 1.2 #1.2
=======
  max_vel_trans: 0.1
  min_vel_trans: 0.0
  max_vel_x: 0.2
  min_vel_x: -0.15
  max_vel_y: 0.
  min_vel_y: 0.
  max_vel_theta: 2.0  # 0.5  
  min_vel_theta: 0.4  # 0.5    
  acc_lim_x: 1.2
>>>>>>> caad1ef3a6570be97c43d15022b40b07c9312fce
  acc_lim_y: 0.
  acc_lim_theta: 15.0   # 15
  acc_lim_trans: 0.5    # 0.5
  

  yaw_goal_tolerance: 0.3 
  xy_goal_tolerance: 0.3
  latch_xy_goal_tolerance: false

  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 3
  vy_samples: 1
  vth_samples: 20
  
  path_distance_bias: 32.  # 32
  goal_distance_bias: 28.
  occdist_scale: 0.01  # 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid: true  # kinetic or obsolete?
  publish_cost_grid_pc: true
  publish_traj_pc: true

  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 10.

  prune_plan: true

  
# Recovery behaviors
conservative_reset:
  reset_distance: 3.0

agressive_reset:
  reset_distance: 4.0
